### PR TITLE
Upgrade jacobsa/fuse

### LINKED ISSUE #548: gcsfuse init fails with "panic: Page size is unexpectedly (big number)" with macFUSE + arm64/m1
* macOS 11.5.1 (20G80)
* arm64 / apple m1 silicon
* macFUSE version 4.1.2, installed with `pkg`
* built `go` from source
* built `gcsfuse` from source w/ GOPATH=$HOME/go
* and:
```
➜  ~ which go
/usr/local/go/bin/go
➜  ~ go version
go version go1.16.6 darwin/arm64
➜  ~ which gcsfuse
/Users/william/go/bin/gcsfuse
➜  ~ gcsfuse
panic: Page size is unexpectedly 16384

goroutine 1 [running]:
github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/fuse/internal/buffer.init.0()
        /Users/william/go/src/github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/fuse/internal/buffer/in_message.go:33 +0xb8
```

any idea what could be causing this?

there's a related issue with macFUSE 4.1.0 (https://github.com/GoogleCloudPlatform/gcsfuse/issues/514) but that seems to be an issue with naming or looking up the name of the macFUSE dependency. my problem seems more system related. 

maybe yet another arm64 compat issue?

### PR DESCRIPTION
**Pull request by gaul**
This addresses incompatibilities with ARM-based Macs and MacFuse >=
4.0.  Fixes #548.  References #514.

### CODE REVIEW

**Comment by gaul** [comment]
@grisaitis Could you try testing with this PR?

**Comment by grisaitis** [comment]
Yes but can you advise on how to handle this?

```
➜  ~ go get -u github.com/gaul/gcsfuse@fuse
go: downloading github.com/gaul/gcsfuse v0.33.4-0.20210904110935-b6f69ffd511c
go get: github.com/gaul/gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c: parsing go.mod:
        module declares its path as: github.com/googlecloudplatform/gcsfuse
                but was required as: github.com/gaul/gcsfuse
```

Sounds like ([SO question](https://stackoverflow.com/questions/56671133/how-to-use-a-forked-module-with-versioned-go-modules-v1-11-go111module-on)) I'd need to edit `go.mod` with a `replace` directive or something... But I don't know how to do this with `go get`.

**Comment by grisaitis** [comment]
I also tried editing `go.mod` in `$GOPATH/pkg/mod/github.com/gaul/gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c`, then tried `go mod vendor`, but got a bunch of errors:

```
➜  gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c go mod vendor
go: downloading github.com/jacobsa/fuse v0.0.0-20210818065549-10d864429bf7
go: downloading golang.org/x/net v0.0.0-20210805182204-aaa1db679c0d
go: downloading github.com/jacobsa/syncutil v0.0.0-20180201203307-228ac8e5a6c3
go: downloading github.com/jacobsa/ogletest v0.0.0-20170503003838-80d50a735a11
go: downloading github.com/jacobsa/gcloud v0.0.0-20210611094250-93436725bc18
go: downloading golang.org/x/oauth2 v0.0.0-20210628180205-a41e5a781914
go: downloading github.com/jacobsa/timeutil v0.0.0-20170205232429-577e5acbbcf6
go: downloading cloud.google.com/go/storage v1.16.0
go: downloading github.com/prometheus/client_golang v1.11.0
go: downloading google.golang.org/api v0.52.0
go: downloading github.com/jacobsa/daemonize v0.0.0-20160101105449-e460293e890f
go: downloading github.com/jacobsa/util v0.0.0-20150810040848-976a6f4de67e
go: downloading github.com/jacobsa/oglematchers v0.0.0-20150720000706-141901ea67cd
go: downloading github.com/kardianos/osext v0.0.0-20190222173326-2bc1f35cddc0
go: downloading cloud.google.com/go v0.88.0
go: downloading github.com/urfave/cli v1.22.5
go: downloading github.com/jacobsa/ratelimit v0.0.0-20150904001804-f5e47030f3b0
go: downloading github.com/jacobsa/oglemock v0.0.0-20150831005832-e94d794d06ff
go: downloading google.golang.org/appengine v1.6.7
go: downloading github.com/jacobsa/reqtrace v0.0.0-20150505043853-245c9e0234cb
go: downloading golang.org/x/sys v0.0.0-20210630005230-0f9fa26af87c
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/prometheus/common v0.26.0
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/golang/protobuf v1.5.2
go: downloading github.com/prometheus/procfs v0.6.0
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0-20190314233015-f79a8a8ca69d
go: downloading github.com/googleapis/gax-go/v2 v2.0.5
go: downloading google.golang.org/genproto v0.0.0-20210722135532-667f2b7c528f
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading google.golang.org/protobuf v1.27.1
go: downloading google.golang.org/grpc v1.39.0
go: downloading go.opencensus.io v0.23.0
go: downloading github.com/jstemmer/go-junit-report v0.9.1
go: downloading golang.org/x/lint v0.0.0-20210508222113-6edffad5e616
go: downloading golang.org/x/tools v0.1.5
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
go: downloading golang.org/x/text v0.3.6
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: downloading golang.org/x/mod v0.4.2
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: finding module for package github.com/googlecloudplatform/gcsfuse/internal/perms
go: finding module for package github.com/googlecloudplatform/gcsfuse/internal/gcsx
go: finding module for package github.com/googlecloudplatform/gcsfuse/internal/mount
go: finding module for package github.com/googlecloudplatform/gcsfuse/internal/canned
go: finding module for package github.com/googlecloudplatform/gcsfuse/internal/logger
go: finding module for package github.com/googlecloudplatform/gcsfuse/internal/auth
go: finding module for package github.com/googlecloudplatform/gcsfuse/internal/perf
go: finding module for package github.com/googlecloudplatform/gcsfuse/internal/fs
go: downloading github.com/googlecloudplatform/gcsfuse v0.36.0
go: finding module for package github.com/googlecloudplatform/gcsfuse/benchmarks/internal/format
go: finding module for package github.com/googlecloudplatform/gcsfuse/benchmarks/internal/percentile
go: finding module for package github.com/googlecloudplatform/gcsfuse/internal/fs/handle
go: finding module for package github.com/googlecloudplatform/gcsfuse/internal/fs/inode
go: finding module for package github.com/googlecloudplatform/gcsfuse/internal/fs/wrappers
go: finding module for package github.com/googlecloudplatform/gcsfuse/tools/util
go: found github.com/googlecloudplatform/gcsfuse/internal/auth in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/internal/canned in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/internal/fs in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/internal/gcsx in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/internal/logger in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/internal/mount in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/internal/perf in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/internal/perms in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/benchmarks/internal/format in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/benchmarks/internal/percentile in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/internal/fs/handle in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/internal/fs/inode in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/internal/fs/wrappers in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/tools/util in github.com/googlecloudplatform/gcsfuse v0.36.0
go: updating go.mod: open /Users/william/go/pkg/mod/github.com/gaul/gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c/go.mod: permission denied
➜  gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c chmod a+w go.mod 
➜  gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c vi go.mod 
➜  gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c go install
main.go:36:2: cannot find package "." in:
        /Users/william/go/pkg/mod/github.com/gaul/gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c/vendor/github.com/googlecloudplatform/gcsfuse/internal/auth
main.go:37:2: cannot find package "." in:
        /Users/william/go/pkg/mod/github.com/gaul/gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c/vendor/github.com/googlecloudplatform/gcsfuse/internal/canned
mount.go:24:2: cannot find package "." in:
        /Users/william/go/pkg/mod/github.com/gaul/gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c/vendor/github.com/googlecloudplatform/gcsfuse/internal/fs
main.go:38:2: cannot find package "." in:
        /Users/william/go/pkg/mod/github.com/gaul/gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c/vendor/github.com/googlecloudplatform/gcsfuse/internal/gcsx
main.go:39:2: cannot find package "." in:
        /Users/william/go/pkg/mod/github.com/gaul/gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c/vendor/github.com/googlecloudplatform/gcsfuse/internal/logger
flags.go:24:2: cannot find package "." in:
        /Users/william/go/pkg/mod/github.com/gaul/gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c/vendor/github.com/googlecloudplatform/gcsfuse/internal/mount
main.go:40:2: cannot find package "." in:
        /Users/william/go/pkg/mod/github.com/gaul/gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c/vendor/github.com/googlecloudplatform/gcsfuse/internal/perf
mount.go:27:2: cannot find package "." in:
        /Users/william/go/pkg/mod/github.com/gaul/gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c/vendor/github.com/googlecloudplatform/gcsfuse/internal/perms
main.go:41:2: cannot find package "." in:
        /Users/william/go/pkg/mod/github.com/gaul/gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c/vendor/github.com/jacobsa/daemonize
main.go:42:2: cannot find package "." in:
        /Users/william/go/pkg/mod/github.com/gaul/gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c/vendor/github.com/jacobsa/fuse
mount.go:29:2: cannot find package "." in:
        /Users/william/go/pkg/mod/github.com/gaul/gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c/vendor/github.com/jacobsa/fuse/fsutil
main.go:43:2: cannot find package "." in:
        /Users/william/go/pkg/mod/github.com/gaul/gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c/vendor/github.com/jacobsa/gcloud/gcs
main.go:44:2: cannot find package "." in:
        /Users/william/go/pkg/mod/github.com/gaul/gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c/vendor/github.com/jacobsa/syncutil
mount.go:30:2: cannot find package "." in:
        /Users/william/go/pkg/mod/github.com/gaul/gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c/vendor/github.com/jacobsa/timeutil
main.go:45:2: cannot find package "." in:
        /Users/william/go/pkg/mod/github.com/gaul/gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c/vendor/github.com/kardianos/osext
main.go:46:2: cannot find package "." in:
        /Users/william/go/pkg/mod/github.com/gaul/gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c/vendor/github.com/prometheus/client_golang/prometheus/promhttp
flags.go:25:2: cannot find package "." in:
        /Users/william/go/pkg/mod/github.com/gaul/gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c/vendor/github.com/urfave/cli
main.go:33:2: cannot find package "." in:
        /Users/william/go/pkg/mod/github.com/gaul/gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c/vendor/golang.org/x/net/context
main.go:34:2: cannot find package "." in:
        /Users/william/go/pkg/mod/github.com/gaul/gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c/vendor/golang.org/x/oauth2
➜  gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c go mod vendor
go: finding module for package github.com/googlecloudplatform/gcsfuse/internal/canned
go: finding module for package github.com/googlecloudplatform/gcsfuse/internal/mount
go: finding module for package github.com/googlecloudplatform/gcsfuse/internal/auth
go: finding module for package github.com/googlecloudplatform/gcsfuse/internal/fs
go: finding module for package github.com/googlecloudplatform/gcsfuse/internal/perms
go: finding module for package github.com/googlecloudplatform/gcsfuse/internal/perf
go: finding module for package github.com/googlecloudplatform/gcsfuse/internal/gcsx
go: finding module for package github.com/googlecloudplatform/gcsfuse/internal/logger
go: finding module for package github.com/googlecloudplatform/gcsfuse/benchmarks/internal/percentile
go: finding module for package github.com/googlecloudplatform/gcsfuse/internal/fs/wrappers
go: finding module for package github.com/googlecloudplatform/gcsfuse/tools/util
go: finding module for package github.com/googlecloudplatform/gcsfuse/benchmarks/internal/format
go: finding module for package github.com/googlecloudplatform/gcsfuse/internal/fs/inode
go: finding module for package github.com/googlecloudplatform/gcsfuse/internal/fs/handle
go: found github.com/googlecloudplatform/gcsfuse/internal/auth in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/internal/canned in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/internal/fs in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/internal/gcsx in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/internal/logger in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/internal/mount in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/internal/perf in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/internal/perms in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/benchmarks/internal/format in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/benchmarks/internal/percentile in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/internal/fs/handle in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/internal/fs/inode in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/internal/fs/wrappers in github.com/googlecloudplatform/gcsfuse v0.36.0
go: found github.com/googlecloudplatform/gcsfuse/tools/util in github.com/googlecloudplatform/gcsfuse v0.36.0
go: updating go.sum: open /Users/william/go/pkg/mod/github.com/gaul/gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c/go.sum: permission denied
➜  gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c sudo go mod vendor
Password:
➜  gcsfuse@v0.33.4-0.20210904110935-b6f69ffd511c sudo go install
package github.com/gaul/gcsfuse
        main.go:36:2: use of internal package github.com/googlecloudplatform/gcsfuse/internal/auth not allowed
package github.com/gaul/gcsfuse
        main.go:37:2: use of internal package github.com/googlecloudplatform/gcsfuse/internal/canned not allowed
package github.com/gaul/gcsfuse
        mount.go:24:2: use of internal package github.com/googlecloudplatform/gcsfuse/internal/fs not allowed
package github.com/gaul/gcsfuse
        main.go:38:2: use of internal package github.com/googlecloudplatform/gcsfuse/internal/gcsx not allowed
package github.com/gaul/gcsfuse
        main.go:39:2: use of internal package github.com/googlecloudplatform/gcsfuse/internal/logger not allowed
package github.com/gaul/gcsfuse
        flags.go:24:2: use of internal package github.com/googlecloudplatform/gcsfuse/internal/mount not allowed
package github.com/gaul/gcsfuse
        main.go:40:2: use of internal package github.com/googlecloudplatform/gcsfuse/internal/perf not allowed
package github.com/gaul/gcsfuse
        mount.go:27:2: use of internal package github.com/googlecloudplatform/gcsfuse/internal/perms not allowed
```

**Comment by gaul** [comment]
You can fetch the pull request instead of my branch to avoid the path problems:

```
git fetch origin pull/552/head:your-branch-name
```

**Comment by grisaitis** [comment]
Thanks so much for the guidance. 

Any chance you could list the other `go` commands I'd need to execute, and in which folders, to get all this to work, starting from `go get`? I'm afraid I just don't know enough about building go applications from source to do this without more beginner-level instructions tbh.

> You can fetch the pull request instead of my branch to avoid the path problems:
> 
> 
> 
> ```
> 
> git fetch origin pull/552/head:your-branch-name
> 
> ```

**Pull request merged**
