### PR TITLE
Upgrades dependencies by dependabot

### PR DESCRIPTION
**Pull request by ankitaluthra1**
### Description

Bump idna from 3.4 to 3.7 in /perfmetrics/scripts

Bump idna from 3.4 to 3.7 in /perfmetrics/scripts/load_tests/python

Bump idna from 3.4 to 3.7 in /perfmetrics/scripts/bigquery

Bump google.golang.org/api from 0.176.1 to 0.177.0

Bump golang.org/x/sys from 0.19.0 to 0.20.0

Bump golang.org/x/oauth2 from 0.19.0 to 0.20.0

### CODE REVIEW

**Comment by raj-prince** [comment]
Can we attach the perf test result? 
Also, we can update the description of PR with direct dependencies we are upgrading.

**Review by ashmeenkaur — APPROVED** [review]
LGTM for go dependency changes. Please update description with direct dependencies being upgraded (and dependabot PR links)

**Review by ashmeenkaur — CHANGES_REQUESTED** [review]
Please add Perf test results as well to ensure no regression

**Comment by ankitaluthra1** [comment]
Updated the PR description  with upgrades, perf test label is added, kokoro ran perf test, I dont see any significant regression
https://fusion2.corp.google.com/ci/kokoro/prod:gcsfuse%2Fgcp_ubuntu%2Fpresubmits%2Fperf_tests%2Fpresubmit/activity/7bf03274-c1c5-481f-a9dd-942ec5e5acb5/log#:~:text=0m27.765s%0Asys%091m48.729s-,showing%20results...,-%2B%2D%2D%2D%2D%2D%2D%2D%2D%2B%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2B%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2B%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2B%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2B%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2B%0A%7C%20Branch%20%7C%20File

**Comment by raj-prince** [comment]
image

**Review by raj-prince — APPROVED** [review]

**Review by ashmeenkaur — APPROVED** [review]

**Pull request merged**
