### PR TITLE
Bump dependabot PRs

### PR DESCRIPTION
**Pull request by Tulsishah**
### Description
This includes
1. https://github.com/GoogleCloudPlatform/gcsfuse/pull/1653
2. https://github.com/GoogleCloudPlatform/gcsfuse/pull/1654
3. https://github.com/GoogleCloudPlatform/gcsfuse/pull/1655
4. https://github.com/GoogleCloudPlatform/gcsfuse/pull/1656
5. https://github.com/GoogleCloudPlatform/gcsfuse/pull/1657
6. https://github.com/GoogleCloudPlatform/gcsfuse/pull/1658
7. https://github.com/GoogleCloudPlatform/gcsfuse/pull/1659
8. https://github.com/GoogleCloudPlatform/gcsfuse/pull/1660
9. https://github.com/GoogleCloudPlatform/gcsfuse/pull/1661
10. https://github.com/GoogleCloudPlatform/gcsfuse/pull/1662

### Link to the issue in case of a bug fix.
NA

### Testing details
1. Manual - NA
2. Unit tests - NA
3. Integration tests - Kokoro
4. Perf tests
image

### CODE REVIEW

**Comment by raj-prince** [comment]
Changes looks good to me.

Just wanted to know, did you upgrade the indirect module separately or is that by-product of upgrading go-storage, go-api?

**Comment by Tulsishah** [comment]
> Changes looks good to me.
> 
> Just wanted to know, did you upgrade the indirect module separately or is that by-product of upgrading go-storage, go-api?

Some of them were by-product, and some I updated according to dependabot PR.

**Comment by raj-prince** [comment]
As discussed offline, it's not a good practice to upgrade only indirect module. As it might change behavior of their direct module. 
Next step:
(a) Create a PR to upgrade the direct dependency.
(b) Let's discuss as a team, how to resolve the issue when we need to upgrade only indirect repo. Two options: (i) We can reach to maintainer of their direct module. (ii) Based on module's changes - are we okay upgrade only the indirect module.

**Comment by sethiay** [comment]
> As discussed offline, it's not a good practice to upgrade only indirect module. As it might change behavior of their direct module. Next step: (a) Create a PR to upgrade the direct dependency module. (b) Let's discuss as a team, how to resolve the issue when we need to upgrade only indirect module. Two options: (i) We can reach to maintainer of their direct module. (ii) Based on module's changes - are we okay upgrade only the indirect module.
> 
> CC: @sethiay @charith87

Agree we shouldn't upgrade indirect dependencies alone. Given that we also need to check https://github.com/GoogleCloudPlatform/gcsfuse/pull/1630 & https://github.com/GoogleCloudPlatform/gcsfuse/pull/1650 PRs accordingly.
CC' @ashmeenkaur , please also don't merge https://github.com/GoogleCloudPlatform/gcsfuse/pull/1664 until we check the above mentioned PRs.

**Comment by ashmeenkaur** [comment]
> > As discussed offline, it's not a good practice to upgrade only indirect module. As it might change behavior of their direct module. Next step: (a) Create a PR to upgrade the direct dependency module. (b) Let's discuss as a team, how to resolve the issue when we need to upgrade only indirect module. Two options: (i) We can reach to maintainer of their direct module. (ii) Based on module's changes - are we okay upgrade only the indirect module.
> > CC: @sethiay @charith87
> 
> Agree we shouldn't upgrade indirect dependencies alone. Given that we also need to check #1630 & #1650 PRs accordingly. CC' @ashmeenkaur , please also don't merge #1664 until we check the above mentioned PRs.

Shall we revert PRs https://github.com/GoogleCloudPlatform/gcsfuse/pull/1630 & https://github.com/GoogleCloudPlatform/gcsfuse/pull/1650? or raise another PR on master that reverts those changes?

**Comment by sethiay** [comment]
> > > As discussed offline, it's not a good practice to upgrade only indirect module. As it might change behavior of their direct module. Next step: (a) Create a PR to upgrade the direct dependency module. (b) Let's discuss as a team, how to resolve the issue when we need to upgrade only indirect module. Two options: (i) We can reach to maintainer of their direct module. (ii) Based on module's changes - are we okay upgrade only the indirect module.
> > > CC: @sethiay @charith87
> > 
> > 
> > Agree we shouldn't upgrade indirect dependencies alone. Given that we also need to check #1630 & #1650 PRs accordingly. CC' @ashmeenkaur , please also don't merge #1664 until we check the above mentioned PRs.
> 
> Shall we revert PRs #1630 & #1650? or raise another PR on master that reverts those changes?

Yes we should revert them and create new PR with only direct dependencies updated (indirect update while updating those direct dependencies are fine)

**Pull request closed without merging**
