### PR TITLE
update vendor packages

### PR DESCRIPTION
**Pull request by mhandugan**
For compatibility with GCS CMEK encryption, this PR refreshes the vendor packages to pick up https://github.com/jacobsa/gcloud/pull/10

This change was created using go-1.13:

```
  go get github.com/googlecloudplatform/gcsfuse
  cd ~/go/src/github.com/googlecloudplatform/gcsfuse
  rm -Rf vendor
  perl -i -pe 's{codegangsta}{urfave}' *.go
  go mod init
  go mod tidy
  go mod vendor
```

The resulting commit was verified to be backward compatible with go-1.10 through a very basic manual test.

### CODE REVIEW

**Comment by bhundven** [comment]
@bjornleffler When can this be reviewed?

**Comment by bjornleffler** [comment]
Thanks for contributing this. I was told there's a new and better way of handling dependencies and meant to investigate that.

Thanks for outlining the steps. A ~360k line change feels far too big to review.

**Comment by sniklaus** [comment]
The actual fix should, to the best of my understanding, only require to update four lines (replacing all occurrences of "codegangsta" with "urfave").

**Comment by bjornleffler** [comment]
Thanks for clarifying.

Gcsfuse has been built with golang 1.10 for a while, as there is a performance/locking bug in golang 1.11+. It's easy to reproduce and only happens under load. I'll test if it's reproducible in 1.14.

**Comment by bjornleffler** [comment]
I'm going to close this PR, as I did it manually. 360k lines of changes is scary to review!

It's included in the .31 release which we're testing.

Thank you so much for this contribution!

**Pull request closed without merging**
