### PR TITLE
Fixes #728: Upgrade Go to 1.18.4

### LINKED ISSUE #728: Upgrade Go runtime to 1.17.12 or 1.18.4 to mitigate CVE vulnerabilities
gcsfuse in its current version is being flagged as a source of multiple Critical CVE vulnerabilities by the security vulnerability scanners such as JFrog XRay or Google on-demand Artifactory Registry scanning because of its dependency on the outdated Go language runtime.

Please upgrade the Go runtime to the latest 1.17.x or 1.18.x versions.

### PR DESCRIPTION
**Pull request by sshcherbakov**
Upgrade Go runtime to the latest version 1.18.4.

### CODE REVIEW

**Comment by vadlakondaswetha** [comment]
Thanks for the PR.
We will update the go version for whole GCSFuse in the next release, so can you revert this cl.

**Comment by sshcherbakov** [comment]
Thank you @vadlakondaswetha 
May I please ask for an approximate timeline for the next release? (Is that days, weeks or months)

**Comment by vadlakondaswetha** [comment]
It will be done in the next 2 weeks.

**Comment by avidullu** [comment]
This has been completed. Please revert this change.
Thanks for your contribution to the project!

**Pull request closed without merging**
