### PR TITLE
It's possible to install gcsfuse on Debian Stretch

### PR DESCRIPTION
**Pull request by idvoretskyi**
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>

### CODE REVIEW

**Comment by idvoretskyi** [comment]
Bump

**Comment by idvoretskyi** [comment]
Ping :)

**Comment by idvoretskyi** [comment]
@cbandy what else is needed to have this merged?

**Comment by cbandy** [comment]
Sorry, I do not know. I'm neither a contributor nor a maintainer.

**Comment by bjornleffler** [comment]
Sorry, didn't see this until now.

**Pull request merged**
