### PR TITLE
Updating go-storage library version

### PR DESCRIPTION
**Pull request by Tulsishah**
1. Added Component Count as part of ObjectAttrs  in Storage Library in new release.
https://github.com/googleapis/google-cloud-go/releases/tag/storage%2Fv1.29.0
2. Performed normal file operations (working fine)
3. Compared fio load test for 50mb file with master branch code 

  bs=1M
  FIlesize=50mb
  Therads = 40

Master

SeqWrite.           BW=80.06MiB/s lat=35912.55ms
RandWrite          BW=81.2MiB/s lat=35244.99ms
SeqRead            BW= 4251.33MiB/s  lat=611.32ms
RandRead.         BW= 1174.33MiB/s lat=2204.02ms

With New Update

SeqWrite.           BW=80.66MiB/s lat=35511.29ms
RandWrite          BW=79.66MiB/s lat=35847.26ms
SeqRead            BW= 4737MiB/s  lat=638.25ms
RandRead.         BW= 1143.33MiB/s lat=2280.23ms

### CODE REVIEW

**Review by raj-prince — CHANGES_REQUESTED** [review]
1. Please update the fio spec for the comparison number.
2. Also, can you please run the fio-test for the same spec for this branch - 2-3 times and do we see any change? Just want to know the variation for the new changes.
3. Did you check - we started getting the Component Count number?

**Review by Tulsishah — COMMENTED** [review]
1. Run FIO test multiple times it is coming in the same range.
2.  Component count is working. this is just added in storage library. I will set it in gcs Object in upcoming PR.

**Comment by raj-prince** [comment]
Performance drop for random read is 21% and random write is 27%, which is a significant drop. This is not in case of sequential read/write. We need to look into this. 

Also, do you have number for jcobsa/gcloud client for the same environments?

**Review by Tulsishah — COMMENTED** [review]
I mistakenly took the bucket and VM in a different region. I experimented again and updated the numbers. Experimented thrice and brought average results.

**Review by raj-prince — APPROVED** [review]

**Pull request merged**
