### PR TITLE
README.md Fixed reference to #467 in markdown

### PR DESCRIPTION
**Pull request by co60ca**

### CODE REVIEW

**Comment by co60ca** [comment]
@googlebot I signed it!

**Comment by lezh** [comment]
The latest release [v0.34.1](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v0.34.1) is supposed to fix the memory consumption issue while keeping the retry behavior.

**Comment by co60ca** [comment]
The readme still has the error in it. Unless you have a patch somewhere else. I wasn’t changing any code just the markdown.

**Comment by lezh** [comment]
Thanks for mentioning. That reference in the README is now removed.

**Pull request closed without merging**
