### PR TITLE
Removing extra logs in kokoro continous test

### PR DESCRIPTION
**Pull request by Tulsishah**
### Description
Removing extra logs in kokoro continous test

### Link to the issue in case of a bug fix.
NA

### Testing details
1. Manual - Tested on kokoro machine for pr perf test.
2. Unit tests - NA
3. Integration tests - NA

### CODE REVIEW

**Comment by raj-prince** [comment]
Can we also do the change here?

dino/setup_container.sh
setup_scripts/setup_container.sh

**Review by raj-prince — CHANGES_REQUESTED** [review]
Please do the similar changes in long haul test script also.

**Comment by Tulsishah** [comment]
> Can we also do the change here?
> 
> dino/setup_container.sh setup_scripts/setup_container.sh

Done

**Review by raj-prince — APPROVED** [review]

**Comment by Tulsishah** [comment]
> Please do the similar changes in long haul test script also.

https://screenshot.googleplex.com/ARjeJr3ch7a7DRG added right?

**Pull request merged**
