### PR TITLE
chore: upgrade go-storage-sdk from 1.43.0 to 1.45.0

### PR DESCRIPTION
**Pull request by raj-prince**
### Description
- Upgrading go-storage-sdk from 1.43.0 to 1.45.0
- Disabling the go-sdk metrics exporter for both grpc and http client.

### Link to the issue in case of a bug fix.
NA

### Testing details
1. Manual - Validated the code of disabled metrics path.
2. Unit tests - NA
3. Integration tests - NA

### CODE REVIEW

**Comment by gargnitingoogle** [comment]
@raj-prince Is `Disabling the go-sdk metrics exporter for both grpc and http client.` related to the go client version upgrade ? If not, then I'd suggest splitting it in a different PR to make it clearer in master branch history.

**Comment by raj-prince** [comment]
> @raj-prince Is `Disabling the go-sdk metrics exporter for both grpc and http client.` related to the go client version upgrade ? If not, then I'd suggest splitting it in a different PR to make it clearer in master branch history.

Yes, go-sdk recently added support for exporter and by default enabled. Hence, we should disable during the update.

**Review by gargnitingoogle — APPROVED** [review]
LGTM

**Comment by raj-prince** [comment]
Another run:

image

**Review by ashmeenkaur — APPROVED** [review]

**Pull request merged**
