### PR TITLE
Upgrade jacobsa/fuse to allow unprivileged mounts on Linux

### PR DESCRIPTION
**Pull request by blinsay**
Upgrades jacobsa/fuse to pick up https://github.com/jacobsa/fuse/pull/124. This allows unprivileged mounts on Linux using libfuse3 style /dev/fd/N mount points.

Upgrading also pulls in support for FUSE_BATCH_FORGET(https://github.com/jacobsa/fuse/pull/123), which required some small changes to the `debugLogging`, `monitoring`, and `errorMapping` filesystems and vectored read support (https://github.com/jacobsa/fuse/commit/c818f6216b48f8211dc693b9b743e5c59fb28c8d) which I didn't try to take advantage of in this PR.

Thanks!

### CODE REVIEW

**Comment by avidullu** [comment]
Thanks for the PR.
Is it possible to not update the vendor library code and only limit the changes to the files local to this repo?
The next release should pick up the changes from vendors if they're already submitted.

**Comment by blinsay** [comment]
> Is it possible to not update the vendor library code and only limit the changes to the files local to this repo?

Sure thing. I get `inconsistent vendoring` errors when I do that, but things seem fine with `-mod=readonly`.

**Comment by avidullu** [comment]
I see some merge conflicts possibly coming from jacobsa/fuse repo.
Would it be easier/smoother if we do a release of gcsfuse and then merge this PR?

**Comment by blinsay** [comment]
Whoops, looks like #673 also upgraded jacobsa/fuse. I rebased on top of that.

**Comment by blinsay** [comment]
@avidullu the CI error looks like the `inconsistent vendoring` error I get trying to build this locally without `-mod=readonly`.

https://github.com/GoogleCloudPlatform/gcsfuse/runs/6911244868?check_suite_focus=true#step:5:18

Happy to do whatever here.

**Comment by avidullu** [comment]
Now I got the reason why you updated the vendor library as well :)

So we will be doing a new release and pulling in the latest jacobsa/fuseutil library on 6/22 . We can merge this PR right before making the release so we pick up this and the changes in jacobsa/fuseutil as well.
Let me know if you think this may have issues.

**Comment by avidullu** [comment]
Hello,
Sorry for the back and forth here. Would it be possible for you to kindly update the vendor directory as well. just like you had in the initial PR? We aren't able to make a new version without those changes. I'll merge the PR immediately after and make a new version of gcsfuse.

Thanks and apologies.
Avi

**Comment by blinsay** [comment]
No worries, just pushed an update with vendored deps.

**Comment by avidullu** [comment]
*Really* appreciate your helping out here!

**Pull request merged**
