### PR TITLE
Dockerfile(s) for images with gcsfuse installed

### PR DESCRIPTION
**Pull request by sethiay**
Changes include:
(a) Addition of Dockerfile for building ubuntu/debian images with gcsfuse package from github release installed. To be used for publishing image to public registry.
(b) Changes in Dockerfile used for building gcsfuse packages to include support for building ubuntu/debian images with those gcsfuse packages installed. This is for building image for testing as part of CI/CD

### CODE REVIEW

**Review by vadlakondaswetha — APPROVED** [review]

**Comment by mattcary** [comment]
Can you add a readme to tools/ explaining how each of these directories is meant to be used? (or point to existing documentation elsewhere in the repo)

I presume that one of these is meant to be an OS image with GCS fuse installed, and the other for a GCSFuse binary to be used on an existing OS? The latter should be based off a distroless build, not a full OS distro.

**Comment by sethiay** [comment]
> Can you add a readme to tools/ explaining how each of these directories is meant to be used? (or point to existing documentation elsewhere in the repo)
> 
> I presume that one of these is meant to be an OS image with GCS fuse installed, and the other for a GCSFuse binary to be used on an existing OS? The latter should be based off a distroless build, not a full OS distro.

Sure, we will add a readme for tools/.

Both the Dockerfiles are meant to create full OS images with gcsfuse installed on them. More details on the files:
1. [containerize_gcsfuse_docker/Dockerfile](https://github.com/GoogleCloudPlatform/gcsfuse/blob/173224e3ac3c7fb7a4a2c53930430bd46fbf0a79/tools/containerize_gcsfuse_docker/Dockerfile): This file is to create Ubuntu and Debian images with latest version of gcsfuse installed on them. The gcsfuse package (.deb file) for installation is downloaded from [GitHub release](https://github.com/GoogleCloudPlatform/gcsfuse/releases) of GCSFuse. The images created with this Dockerfile is to be uploaded to public registry.
2. [package_gcsfuse_docker/Dockerfile](https://github.com/GoogleCloudPlatform/gcsfuse/blob/173224e3ac3c7fb7a4a2c53930430bd46fbf0a79/tools/package_gcsfuse_docker/Dockerfile): This Dockerfile has two purposes:
    - Build with --target [gcsfuse_packages](https://github.com/GoogleCloudPlatform/gcsfuse/blob/173224e3ac3c7fb7a4a2c53930430bd46fbf0a79/tools/package_gcsfuse_docker/Dockerfile#L30) to be used for building gcsfuse packages (.deb for .rpm files) for uploading to GCSFuse releases on GitHub. This builds gcsfuse packages using the code on master branch.
    - The other layer of this Dockerfile to be used for building Ubuntu and Debian images with the gcsfuse packages from --target gcsfuse_packages installed on it. The purpose of these images is to perform some CI/CD tests on these images.
    
We will be specifically using Ubuntu and Debian as base images because we support gcsfuse on these OS.

**Comment by mattcary** [comment]
You use distroless for security, there's a much smaller surface for CVEs. There's rarely a need to pull in an entire OS distro.

That said, I'm going to have to look more closely at this. Your pulling down a deb package rather than just building a version from this repo is not standard, how to guarantee provenance of the image?

Probably we should sync offline so  I can understand what your intended use cases are.

**Comment by mattcary** [comment]
lgtm, with a minor nit. Thanks!

**Pull request merged**
