### PR TITLE
Rebase release branch to master branch

### PR DESCRIPTION
**Pull request by gargnitingoogle**
Rebase release branch to master to keep it up-to-date with the changes on master branch.

### CODE REVIEW

**Review by vadlakondaswetha — COMMENTED** [review]
We should do re-base and not merge

**Comment by gargnitingoogle** [comment]
> We should do re-base and not merge

I planned to rebase (`rebase and merge`) only, not merge. I've now changed the title and the description accordingly.

**Comment by gargnitingoogle** [comment]
This is blocked on https://github.com/GoogleCloudPlatform/gcsfuse/pull/1403 .

**Comment by gargnitingoogle** [comment]
Closing this as this is not a good idea. Rebasing release branch to master branch head will make the reverse more difficult (as it'll cause conflicts), which is required for getting all features meant for release into the master branch.

**Comment by gargnitingoogle** [comment]
Closing.

**Pull request closed without merging**
